// ============================================================
// Auto-generated by: npx supabase gen types typescript
// Run: npm run db:types
// ============================================================
// This is a placeholder. After connecting to Supabase, run:
//   npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          phone: string | null;
          address_line1: string | null;
          address_line2: string | null;
          city: string | null;
          state: string | null;
          zip: string | null;
          is_first_order_used: boolean;
          total_spent: number;
          order_count: number;
          marketing_consent: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          name?: string | null;
          phone?: string | null;
          address_line1?: string | null;
          address_line2?: string | null;
          city?: string | null;
          state?: string | null;
          zip?: string | null;
          is_first_order_used?: boolean;
          total_spent?: number;
          order_count?: number;
          marketing_consent?: boolean;
        };
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>;
      };
      products: {
        Row: {
          id: string;
          name: string;
          name_ko: string | null;
          slug: string;
          description: string | null;
          description_ko: string | null;
          price: number;
          original_price: number | null;
          cost_price: number | null;
          product_type: 'preorder' | 'instock';
          category: 'beauty' | 'fashion' | 'food' | 'health' | 'kitchen' | 'kids' | 'living' | 'etc';
          status: 'draft' | 'active' | 'soldout' | 'archived';
          total_slots: number;
          sold_count: number;
          images: string[];
          thumbnail: string | null;
          detail_tabs: Json;
          tags: string[];
          sort_order: number;
          is_featured: boolean;
          group_buy_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          name: string;
          slug: string;
          price: number;
          product_type: 'preorder' | 'instock';
          category: 'beauty' | 'fashion' | 'food' | 'health' | 'kitchen' | 'kids' | 'living' | 'etc';
          name_ko?: string | null;
          description?: string | null;
          description_ko?: string | null;
          original_price?: number | null;
          cost_price?: number | null;
          status?: 'draft' | 'active' | 'soldout' | 'archived';
          total_slots?: number;
          images?: string[];
          thumbnail?: string | null;
          detail_tabs?: Json;
          tags?: string[];
          sort_order?: number;
          is_featured?: boolean;
          group_buy_id?: string | null;
        };
        Update: Partial<Database['public']['Tables']['products']['Insert']>;
      };
      orders: {
        Row: {
          id: string;
          order_number: string;
          customer_id: string | null;
          customer_email: string;
          customer_name: string;
          customer_phone: string | null;
          fulfillment_type: 'pickup' | 'shipping';
          shipping_address: Json | null;
          payment_method: 'zelle' | 'venmo';
          payment_reference: string | null;
          payment_confirmed_at: string | null;
          subtotal: number;
          shipping_fee: number;
          discount_amount: number;
          discount_code: string | null;
          total: number;
          status: 'pending' | 'paid' | 'preparing' | 'ready_pickup' | 'ready_ship' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
          customer_note: string | null;
          admin_note: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          customer_email: string;
          customer_name: string;
          payment_method: 'zelle' | 'venmo';
          subtotal: number;
          total: number;
          order_number?: string;
          customer_id?: string | null;
          customer_phone?: string | null;
          fulfillment_type?: 'pickup' | 'shipping';
          shipping_address?: Json | null;
          payment_reference?: string | null;
          shipping_fee?: number;
          discount_amount?: number;
          discount_code?: string | null;
          status?: 'pending' | 'paid' | 'preparing' | 'ready_pickup' | 'ready_ship' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
          customer_note?: string | null;
          admin_note?: string | null;
        };
        Update: Partial<Database['public']['Tables']['orders']['Insert']>;
      };
      order_items: {
        Row: {
          id: string;
          order_id: string;
          product_id: string | null;
          product_name: string;
          product_image: string | null;
          product_price: number;
          quantity: number;
          subtotal: number;
          selected_options: Json;
          created_at: string;
        };
        Insert: {
          order_id: string;
          product_name: string;
          product_price: number;
          quantity: number;
          subtotal: number;
          product_id?: string | null;
          product_image?: string | null;
          selected_options?: Json;
        };
        Update: Partial<Database['public']['Tables']['order_items']['Insert']>;
      };
      cart_items: {
        Row: {
          id: string;
          user_id: string;
          product_id: string;
          quantity: number;
          selected_options: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          product_id: string;
          quantity?: number;
          selected_options?: Json;
        };
        Update: Partial<Database['public']['Tables']['cart_items']['Insert']>;
      };
      group_buys: {
        Row: {
          id: string;
          title: string;
          title_ko: string | null;
          description: string | null;
          status: 'upcoming' | 'active' | 'closed' | 'completed';
          open_at: string;
          close_at: string;
          estimated_arrival: string | null;
          total_orders: number;
          total_revenue: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          title: string;
          open_at: string;
          close_at: string;
          title_ko?: string | null;
          description?: string | null;
          status?: 'upcoming' | 'active' | 'closed' | 'completed';
          estimated_arrival?: string | null;
        };
        Update: Partial<Database['public']['Tables']['group_buys']['Insert']>;
      };
      site_settings: {
        Row: {
          key: string;
          value: Json;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          key: string;
          value: Json;
          updated_by?: string | null;
        };
        Update: {
          value?: Json;
          updated_by?: string | null;
        };
      };
      subscribers: {
        Row: {
          id: string;
          email: string;
          name: string | null;
          is_active: boolean;
          source: string;
          subscribed_at: string;
          unsubscribed_at: string | null;
        };
        Insert: {
          email: string;
          name?: string | null;
          source?: string;
        };
        Update: Partial<Database['public']['Tables']['subscribers']['Insert']>;
      };
      email_logs: {
        Row: {
          id: string;
          recipient_email: string;
          email_type: 'welcome' | 'order_confirmation' | 'preparing' | 'ready_pickup' | 'magic_link';
          subject: string | null;
          resend_id: string | null;
          order_id: string | null;
          status: string;
          metadata: Json;
          created_at: string;
        };
        Insert: {
          recipient_email: string;
          email_type: 'welcome' | 'order_confirmation' | 'preparing' | 'ready_pickup' | 'magic_link';
          subject?: string | null;
          resend_id?: string | null;
          order_id?: string | null;
          status?: string;
          metadata?: Json;
        };
        Update: Partial<Database['public']['Tables']['email_logs']['Insert']>;
      };
      admin_users: {
        Row: {
          id: string;
          user_id: string | null;
          email: string;
          role: 'super' | 'manager' | 'viewer';
          is_active: boolean;
          created_at: string;
        };
        Insert: {
          email: string;
          user_id?: string | null;
          role?: 'super' | 'manager' | 'viewer';
          is_active?: boolean;
        };
        Update: Partial<Database['public']['Tables']['admin_users']['Insert']>;
      };
      magic_links: {
        Row: {
          id: string;
          email: string;
          token: string;
          expires_at: string;
          used_at: string | null;
          created_at: string;
        };
        Insert: {
          email: string;
          token: string;
          expires_at: string;
        };
        Update: {
          used_at?: string | null;
        };
      };
    };
    Enums: {
      product_status: 'draft' | 'active' | 'soldout' | 'archived';
      product_type: 'preorder' | 'instock';
      product_category: 'beauty' | 'fashion' | 'food' | 'health' | 'kitchen' | 'kids' | 'living' | 'etc';
      order_status: 'pending' | 'paid' | 'preparing' | 'ready_pickup' | 'ready_ship' | 'shipped' | 'delivered' | 'cancelled' | 'refunded';
      payment_method: 'zelle' | 'venmo';
      fulfillment_type: 'pickup' | 'shipping';
      group_buy_status: 'upcoming' | 'active' | 'closed' | 'completed';
      email_type: 'welcome' | 'order_confirmation' | 'preparing' | 'ready_pickup' | 'magic_link';
      admin_role: 'super' | 'manager' | 'viewer';
    };
  };
};

// Convenience types
export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Product = Database['public']['Tables']['products']['Row'];
export type Order = Database['public']['Tables']['orders']['Row'];
export type OrderItem = Database['public']['Tables']['order_items']['Row'];
export type CartItem = Database['public']['Tables']['cart_items']['Row'];
export type GroupBuy = Database['public']['Tables']['group_buys']['Row'];
export type SiteSetting = Database['public']['Tables']['site_settings']['Row'];
export type Subscriber = Database['public']['Tables']['subscribers']['Row'];
export type EmailLog = Database['public']['Tables']['email_logs']['Row'];
export type AdminUser = Database['public']['Tables']['admin_users']['Row'];
